#!/bin/bash

# ------------------------------------------------------------------------------
# @d3af90d 2025-06-01 23:33.17
#          2025-06-11 01:19.10 (last edit)
#
# rfcp - [r]e[f]resh [c]o[p]yright
# cat file | rfcp
# :%!rfcp
#
# oneliner to refresh the 'last edit' line of these headers
# ------------------------------------------------------------------------------

sed "5s|^\([^[[:space:]]]*[[:space:]]*\).*$|\1$(date '+%Y-%m-%d %H:%M.%S') (last edit)|"
